In [1]:
%pip install pandas

     |████████████████████████████████| 12.4 MB 20.2 MB/s eta 0:00:01
     |████████████████████████████████| 17.3 MB 54.7 MB/s eta 0:00:01
     |████████████████████████████████| 345 kB 58.8 MB/s eta 0:00:01
     |████████████████████████████████| 505 kB 58.5 MB/s eta 0:00:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({'col1' : [1,2,3,4,5],
              'col2' : [45,56,67,34,34],
              'col3': "sudhanshu kumar krish ineuron one".split()
     })

In [4]:
"sudhanshu kumar krish ineuron one".split()

['sudhanshu', 'kumar', 'krish', 'ineuron', 'one']

In [5]:
df

col1  col2       col3
0     1    45  sudhanshu
1     2    56      kumar
2     3    67      krish
3     4    34    ineuron
4     5    34        one

In [6]:
df['col4'] = df['col1']**2

In [7]:
df

col1  col2       col3  col4
0     1    45  sudhanshu     1
1     2    56      kumar     4
2     3    67      krish     9
3     4    34    ineuron    16
4     5    34        one    25

In [8]:
df['col5'] = df['col3'].str[0]

In [9]:
df

col1  col2       col3  col4 col5
0     1    45  sudhanshu     1    s
1     2    56      kumar     4    k
2     3    67      krish     9    k
3     4    34    ineuron    16    i
4     5    34        one    25    o

In [10]:
def test(a) :
    return a**2

In [11]:
df['col4_4']  = df['col1'].apply(test)

In [12]:
df

col1  col2       col3  col4 col5  col4_4
0     1    45  sudhanshu     1    s       1
1     2    56      kumar     4    k       4
2     3    67      krish     9    k       9
3     4    34    ineuron    16    i      16
4     5    34        one    25    o      25

In [13]:
def test1(a):
    if a =='s':
        return 's'
    else:
        return 'z'

In [14]:
df['col6'] = df['col5'].apply(test1)

In [15]:
df

col1  col2       col3  col4 col5  col4_4 col6
0     1    45  sudhanshu     1    s       1    s
1     2    56      kumar     4    k       4    z
2     3    67      krish     9    k       9    z
3     4    34    ineuron    16    i      16    z
4     5    34        one    25    o      25    z

In [16]:
df['col6_6'] = df['col5'].apply(lambda a : 's' if a == 's' else 'z')

In [17]:
df

col1  col2       col3  col4 col5  col4_4 col6 col6_6
0     1    45  sudhanshu     1    s       1    s      s
1     2    56      kumar     4    k       4    z      z
2     3    67      krish     9    k       9    z      z
3     4    34    ineuron    16    i      16    z      z
4     5    34        one    25    o      25    z      z

In [18]:
df['col7'] = df['col3'].apply(len)

In [19]:
df

col1  col2       col3  col4 col5  col4_4 col6 col6_6  col7
0     1    45  sudhanshu     1    s       1    s      s     9
1     2    56      kumar     4    k       4    z      z     5
2     3    67      krish     9    k       9    z      z     5
3     4    34    ineuron    16    i      16    z      z     7
4     5    34        one    25    o      25    z      z     3

In [20]:
import math

In [21]:
df['col8'] = df['col2'].apply(math.log)

In [22]:
df

col1  col2       col3  col4 col5  col4_4 col6 col6_6  col7      col8
0     1    45  sudhanshu     1    s       1    s      s     9  3.806662
1     2    56      kumar     4    k       4    z      z     5  4.025352
2     3    67      krish     9    k       9    z      z     5  4.204693
3     4    34    ineuron    16    i      16    z      z     7  3.526361
4     5    34        one    25    o      25    z      z     3  3.526361

From ChatGPT:

NumPy (Numerical Python) is a powerful Python library used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is the foundation of many other Python scientific computing libraries, such as SciPy, pandas, and scikit-learn.

With NumPy, you can perform various operations on arrays, like mathematical, logical, shape manipulation, sorting, selecting, input/output, and linear algebra operations. It's widely used in fields such as physics, astronomy, engineering, finance, and data science for its efficiency and ease of use in handling numerical data.

In [23]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [24]:
import numpy as np

In [25]:
l = ["sudh" , 1,2,3,4]

In [26]:
type(l)

list

In [27]:
np.array(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U21')

In [28]:
type(np.array(l))  #ndarray mean n-dim array

numpy.ndarray

In [29]:
a1 = np.array([3,4,5,6,3.0])

In [30]:
a1  #as we used 3.0, therefore all values converted into float

array([3., 4., 5., 6., 3.])

In [31]:
a = np.array([[1,2] , [3,4]])

In [32]:
a

array([[1, 2],
       [3, 4]])

In [33]:
a[1][1]

4

In [34]:
a1[1]

4.0

In [35]:
a2 = np.array([1,2,3,4],ndmin = 4) #ndim = 0 by default

In [36]:
a2

array([[[[1, 2, 3, 4]]]])

In [37]:
a2[0][0][0][0]

1

In [38]:
a

array([[1, 2],
       [3, 4]])

In [39]:
np.asarray([1,2,3,4,5]) #np.array,np.asarray & np.asanyarray all are almost same with minor differences

array([1, 2, 3, 4, 5])

In [40]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [41]:
np.mat([1,2,3,4,5])   #mat means matrices. It has minimum 2 dimension

matrix([[1, 2, 3, 4, 5]])

In [42]:
a = [1,2,3,4,5]
np.asarray(a)   #coverted list into array

array([1, 2, 3, 4, 5])

In [43]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [44]:
np.asanyarray(a)   #It converts only if already not an array (a is a list so converted)

array([1, 2, 3, 4, 5])

In [45]:
np.asanyarray(np.mat(a)) #already an array(2 dim)

matrix([[1, 2, 3, 4, 5]])

In [46]:
np.fromfunction(lambda i , j : i==j , (3,3)) #dim = (3,3), if i==j return true else false

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [47]:
np.fromfunction(lambda i , j: i*j, (4,4),dtype = int)  #by default dtype = float 
#i and j are representing rows and columns

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [48]:
np.fromfunction(lambda i , j ,z ,p: i*j*z*p , (4,3,2,2),dtype = int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [68]:
a = np.fromfunction(lambda i , j ,z : i*j*z , (4,3,2),dtype = int)

In [69]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [50]:
a.ndim

3

In [51]:
a.size   #total no. of elements in an array

24

In [52]:
a.shape

(4, 3, 2)

In [53]:
a.dtype #inside numpy there are 16,32 & 64 bit integer. By default it is 32 bit

dtype('int64')

In [54]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [84]:
pd.DataFrame(a)  #It will give error "ValueError: Must pass 2-d input. shape=(4, 3, 2)"

ValueError: Must pass 2-d input. shape=(4, 3, 2)

The reshape() function in NumPy allows you to change the shape of an array while keeping the same underlying data. It doesn't change the data itself; it merely changes how the data is interpreted in terms of its dimensions.
so to fix the above error we can simply change the dimension to 2-D

In [72]:
a.reshape(12,2) #as 'a' was having total 24 elements so the reshaped dimension should also equal to 24 elements i.e. 12*2 = 24

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [67]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [70]:
a.reshape(2,6,2) #as 'a' was having total 24 elements so the reshaped dimension should also equal to 24 elements i.e. 2*6*2 = 24

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4],
        [0, 0],
        [0, 3],
        [0, 6]]])

In [74]:
a.reshape(2,4,-234)
#This line reshapes the array 'a' into a new shape '(2, 4, -234)'. The `-234` in the shape tuple indicates that NumPy should automatically compute the size of that dimension to ensure the total number of elements remains unchanged. 
#generally we use -1 when we want autmatic selection of the dimension
#always remember nly one value can be put -ve i.e. this is wrong (-1,2,-1) 
#i.e. in this case dimension would be automatically become (2,4,3)

array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 2],
        [0, 0, 0, 2, 0, 4],
        [0, 0, 0, 3, 0, 6]]])

In [55]:
a = np.fromfunction(lambda i , j : i*j , (400,100),dtype = int) #in this way we can generate a random 2d array of any length which can be then converted into a dataframe
#sometime we need such dataframe for system testing

In [56]:
a

array([[    0,     0,     0, ...,     0,     0,     0],
       [    0,     1,     2, ...,    97,    98,    99],
       [    0,     2,     4, ...,   194,   196,   198],
       ...,
       [    0,   397,   794, ..., 38509, 38906, 39303],
       [    0,   398,   796, ..., 38606, 39004, 39402],
       [    0,   399,   798, ..., 38703, 39102, 39501]])

In [57]:
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]

In [59]:
np.random.rand(100,4)

array([[2.59519848e-01, 1.10832711e-01, 7.59651535e-01, 7.09534597e-01],
       [8.75081795e-01, 7.69526418e-01, 1.91423451e-01, 9.89984650e-01],
       [5.13679852e-01, 7.26039584e-01, 8.83673992e-01, 9.61439041e-01],
       [4.89547932e-01, 4.79993032e-01, 5.35797377e-01, 5.10128478e-01],
       [6.50719860e-01, 7.47308637e-01, 5.55846352e-01, 4.73230775e-01],
       [4.82747056e-01, 4.00799034e-01, 2.21074381e-01, 1.31628955e-02],
       [4.25979058e-01, 8.67043947e-01, 9.01576812e-01, 5.37270050e-01],
       [1.25947900e-01, 5.17716424e-01, 8.81608414e-01, 4.11092157e-01],
       [4.54970683e-01, 6.35856814e-01, 5.05860763e-01, 8.63714101e-01],
       [6.61841271e-01, 1.10197667e-02, 7.13320722e-01, 4.32344753e-01],
       [7.40275542e-01, 7.06667594e-01, 2.27914798e-01, 3.99376174e-01],
       [7.67922996e-01, 1.44172247e-01, 5.58693055e-01, 4.54471163e-01],
       [2.88243645e-01, 4.78086091e-01, 5.73705763e-02, 8.02529513e-01],
       [2.87170520e-01, 9.55998240e-01, 2.75392731e

In [62]:
help(np.random.rand) #always remember to use help to know the definition of function

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [63]:
np.random.randint(4,50) #any integer between 4 and 50

40

In [64]:
pd.DataFrame(np.random.randn(4,5)) #randn is similiar to rand but randn gives random no. with normal distribution
#i.e. average = 0 and stand. dev. (S.D) = 1

0         1         2         3         4
0  0.552994  0.648357 -0.112381  0.085408 -0.797476
1 -0.318170 -0.944551 -2.291617 -0.715868  0.056973
2  1.267710 -0.100231  0.273271 -0.077756  0.014071
3 -1.306972  0.799499  0.992821  1.285907 -0.376107

In [77]:
list(range(4,10.5,2))  #error, bcz range function always takes integer value only
#list(range(4,10,.2))   #error, bcz range function always takes integer value only
#list(range(4,10,2))    #this will work fine

TypeError: 'float' object cannot be interpreted as an integer

In [78]:
a1 = np.arange(4,10.5,.2) #in numpy we are having arange similiar to range function but it takes float value as well

In [79]:
a1

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [80]:
a1[1:4] #slicing operation

array([4.2, 4.4, 4.6])

In [81]:
arr = np.random.rand(4,5)

In [82]:
arr

array([[0.80082825, 0.47040257, 0.05626057, 0.27657699, 0.60694931],
       [0.75988505, 0.84896954, 0.4344289 , 0.81433051, 0.55521476],
       [0.73829466, 0.23301508, 0.26727219, 0.42588365, 0.93161449],
       [0.73120062, 0.66005249, 0.01260113, 0.73943974, 0.46331767]])

In [84]:
arr > .5

array([[ True, False, False, False,  True],
       [ True,  True, False,  True,  True],
       [ True, False, False, False,  True],
       [ True,  True, False,  True, False]])

In [83]:
arr[arr > .5] #to get all the no. greater than .5

array([0.80082825, 0.60694931, 0.75988505, 0.84896954, 0.81433051,
       0.55521476, 0.73829466, 0.93161449, 0.73120062, 0.66005249,
       0.73943974])

In [85]:
arr

array([[0.80082825, 0.47040257, 0.05626057, 0.27657699, 0.60694931],
       [0.75988505, 0.84896954, 0.4344289 , 0.81433051, 0.55521476],
       [0.73829466, 0.23301508, 0.26727219, 0.42588365, 0.93161449],
       [0.73120062, 0.66005249, 0.01260113, 0.73943974, 0.46331767]])

In [87]:
arr[[1,2] , [2]]  #we want particular data from array. In this case we want data available at position (1,2) & (2,2) i.e. 0.4344289 & 0.26727219
#[1,2] represents the row and [2] represents the coulumn
#we know we can also convert this in dataframe and can do the same task in dataframe with loc and iloc

array([0.4344289 , 0.26727219])

In [88]:
arr = np.random.rand(8,5)

In [89]:
arr

array([[0.34229254, 0.994678  , 0.47254948, 0.6759967 , 0.00197076],
       [0.71879872, 0.97942226, 0.66279358, 0.74270746, 0.10208525],
       [0.77171633, 0.3515104 , 0.33413144, 0.24418247, 0.98475587],
       [0.59441808, 0.14195496, 0.18720303, 0.83734688, 0.92008869],
       [0.99656427, 0.35758394, 0.9673329 , 0.46556335, 0.16774544],
       [0.63712463, 0.45735805, 0.10428758, 0.20839248, 0.39515252],
       [0.70373355, 0.78112612, 0.73286284, 0.49174437, 0.03854835],
       [0.54407001, 0.24512127, 0.29438569, 0.48455504, 0.99460592]])

In [141]:
arr[1:8 , 0:3]

array([[0.42606827, 0.22185603, 0.58923839],
       [0.27972671, 0.05201551, 0.20664134],
       [0.52289791, 0.47277745, 0.57308363],
       [0.99077719, 0.73536865, 0.80803739],
       [0.60878245, 0.82748183, 0.34073401],
       [0.8256555 , 0.66887215, 0.34532617],
       [0.34353465, 0.99218211, 0.58638314]])

In [91]:
a2 = arr[1:8 , [0,1,2]] #remember, you can't write it as: arr[[1,2,3,4,5,6,7] , [1,2,3]] but you can write it as: arr[[1,2,3,4,5,6,7] , 0:3] why? -> understand yourself

In [92]:
a2

array([[0.71879872, 0.97942226, 0.66279358],
       [0.77171633, 0.3515104 , 0.33413144],
       [0.59441808, 0.14195496, 0.18720303],
       [0.99656427, 0.35758394, 0.9673329 ],
       [0.63712463, 0.45735805, 0.10428758],
       [0.70373355, 0.78112612, 0.73286284],
       [0.54407001, 0.24512127, 0.29438569]])

In [96]:
a2[0][0] = 100 #to change data at particular index

In [97]:
a2

array([[100.        ,   0.97942226,   0.66279358],
       [  0.77171633,   0.3515104 ,   0.33413144],
       [  0.59441808,   0.14195496,   0.18720303],
       [  0.99656427,   0.35758394,   0.9673329 ],
       [  0.63712463,   0.45735805,   0.10428758],
       [  0.70373355,   0.78112612,   0.73286284],
       [  0.54407001,   0.24512127,   0.29438569]])

In [98]:
a = np.array([[1,2] ,[3,4]])
b = np.array([[2,3] , [4,5]])

In [101]:
a

array([[1, 2],
       [3, 4]])

In [100]:
b

array([[2, 3],
       [4, 5]])

In [102]:
a*b #element-wise multiplication and not matrix multiplication

array([[ 2,  6],
       [12, 20]])

In [103]:
m = a@b #matrix multiplication, remember it

In [104]:
m

array([[10, 13],
       [22, 29]])

In [105]:
m/0

/tmp/ipykernel_366/3791875896.py:1: RuntimeWarning: divide by zero encountered in divide
  m/0


array([[inf, inf],
       [inf, inf]])