In [54]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [55]:
import numpy as np 

In [56]:
l = [1,2,3,4,54]

In [57]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [58]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [60]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [61]:
np.ones((3,6,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [62]:
5+np.zeros((3,4)) #broadcasting: if we are trying to perform a same kind of operation with all the elements which are available in my space
#here adiition of 5 is broadcasting to all the elements of the matrix

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [63]:
np.empty((5,4,2)) #it will give values nearer to zero. you can see in the output e-316 which means 10^-316 which is a very small value

array([[[1.45134669e-316, 0.00000000e+000],
        [6.93327266e-310, 8.20430627e-304],
        [8.20430627e-304, 8.20430627e-304],
        [8.20430627e-304, 8.20430627e-304]],

       [[8.20430627e-304, 8.20430627e-304],
        [8.20430627e-304, 8.20430627e-304],
        [8.20430627e-304, 8.20430627e-304],
        [8.20430627e-304, 8.20430627e-304]],

       [[8.20430811e-304, 8.21678743e-304],
        [2.13290380e-260, 9.16250181e-246],
        [5.95721976e-212, 4.79418579e-270],
        [1.32238577e-279, 2.52217118e-284]],

       [[7.20004044e-251, 1.04728959e+121],
        [6.70676604e-111, 7.58828693e-270],
        [5.65633146e+303, 6.05971060e-039],
        [1.65628495e+304, 2.42659321e-279]],

       [[3.12997838e-178, 3.91518628e-294],
        [1.60679699e-245, 1.33735963e-081],
        [8.00328603e-082, 1.38494594e+304],
        [2.23469033e+304, 3.73847474e-217]]])

The np.linspace() function in NumPy is used to create an array of evenly spaced values over a specified interval. The function can also return the step size used to create the array if retstep=True is specified.

In [64]:
np.linspace(2,6,100,endpoint=False,retstep=True) #It will generate 100 no's from 2 to 6. bydefault endpoint = True i.e. 6 is also included
#bydefault retstep = false
# we can see in the output, the step size = 0.04
# 100 represents number of samples to generate. bydefault it is 50
# it is in 1-D but we can convert it in any dimension with reshape

(array([2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96, 4.  , 4.04, 4.08, 4.12, 4.16,
        4.2 , 4.24, 4.28, 4.32, 4.36, 4.4 , 4.44, 4.48, 4.52, 4.56, 4.6 ,
        4.64, 4.68, 4.72, 4.76, 4.8 , 4.84, 4.88, 4.92, 4.96, 5.  , 5.04,
        5.08, 5.12, 5.16, 5.2 , 5.24, 5.28, 5.32, 5.36, 5.4 , 5.44, 5.48,
        5.52, 5.56, 5.6 , 5.64, 5.68, 5.72, 5.76, 5.8 , 5.84, 5.88, 5.92,
        5.96]),
 0.04)

The np.logspace() function in NumPy is used to generate numbers that are evenly spaced on a logarithmic scale. The base parameter specifies the base of the logarithm.

In [65]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [66]:
np.linspace(2,4,10) #jobhi no's upr generate hue hai agr unka log nikalenge with base 2, we will get this output

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [67]:
a = np.arange(4,40).reshape(6,6)

In [68]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [69]:
a.max()

39

In [70]:
a.max(axis = 0) #axis = 0 means row and axis = 1 means column #maybe output dkhke kch confusion ho row-wise and col-wise smjhne mei but easy hai smjh jayega thoda deep thinking se

array([34, 35, 36, 37, 38, 39])

In [71]:
a.max(axis = 1)

array([ 9, 15, 21, 27, 33, 39])

In [72]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [73]:
10+ a

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [74]:
a/0

/tmp/ipykernel_307/4102073204.py:1: RuntimeWarning: divide by zero encountered in divide
  a/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [75]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [76]:
a**3

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]])

In [77]:
pow(a,3)

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]])

In [78]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [79]:
b = np.array([2,3,1,2,3,4])

In [80]:
a+b #broadcasting row wise

array([[ 6,  8,  7,  9, 11, 13],
       [12, 14, 13, 15, 17, 19],
       [18, 20, 19, 21, 23, 25],
       [24, 26, 25, 27, 29, 31],
       [30, 32, 31, 33, 35, 37],
       [36, 38, 37, 39, 41, 43]])

In [81]:
b = b.reshape(1,-1) #for col wise broadcasting, first we need to convert the array from 1D to 2D
#b.reshape(-1,1) #or we can directly reshape it in col. wise
b

array([[2, 3, 1, 2, 3, 4]])

In [82]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [83]:
b.T +a #col wise broadcasting. T means transpose

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [38, 39, 40, 41, 42, 43]])

In [84]:
 b.T

array([[2],
       [3],
       [1],
       [2],
       [3],
       [4]])

In [85]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [86]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [87]:
np.exp(a) #e^a

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [88]:
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [139]:
x = np.array([1,2,3])

In [140]:
y = x #Shallow Copy

A shallow copy of an object is a new object whose contents are references to the original elements. If the elements themselves are mutable objects, changes to these elements will be reflected in both the original and the copied object. However, the shallow copy itself is a distinct object from the original.

In [141]:
y

array([1, 2, 3])

In [142]:
z = np.copy(x) #deepcopy

A deep copy of an object is a new object that is a recursive copy of the original object and all objects contained within it. Changes to the new object do not affect the original object, and vice versa, even if the elements are mutable.

In [143]:
z

array([1, 2, 3])

In [144]:
x[0] = 100

In [145]:
y

array([100,   2,   3])

In [146]:
z

array([1, 2, 3])

The id() function in Python is used to obtain the unique identifier (memory address) of an object. This identifier is unique for the object during its lifetime.

Usage:

The id() function can be used to understand how objects are referenced in memory, which is particularly useful when dealing with mutable and immutable objects.

In [147]:
id(z)

140330998099664

In [148]:
id(x)

140330998005904

In [149]:
id(y)

140330998005904

In [150]:
x

array([100,   2,   3])

In [151]:
id(x[0])

140330997920176

In [152]:
y

array([100,   2,   3])

In [153]:
id(y[0]) #not same as id(x[0]). why?

140330997921456

Reason for Different IDs:
When you access an element of a numpy array using indexing, numpy returns a numpy scalar object. Each time you access an element, a new scalar object is created, even if the value is the same.

In [154]:
id(x[1])

140330997922352

In [155]:
id(y[1])

140331001420528

In [156]:
id(z[1])

140330997922448

In [129]:
su = np.array([2,567,345])

In [130]:
df = su

In [131]:
id(su)

140330998030672

In [132]:
id(df)

140330998030672

In [133]:
id(su[0])

140330997920784

In [134]:
id(df[0])

140330997922032

In [135]:
id(su[1])

140330997921040

In [136]:
id(df[1])

140330997922128

In [137]:
id(su[0]) == id(df[0])    

True

In [138]:
id(su[1]) == id(df[0]) 
#Remember following is not the correect reason but I thought it might be, therefore I am not removing the comment
#Real reason which I found on website, is given after some blocks of code below
#By Nirbhay: I think it can be due to the same base address. May be as I had read in C++, base address of both su and df are same,
#so may be it is returning true on the basis of their base address

True

In [160]:
id(x[0]) == id(z[0])

True

In [124]:
id(su) == id(df)

True

In [178]:
xt = np.array([34,67,89])

In [172]:
id(xt[0]) == id(su[0])

True

As you know this: When you access an element of a numpy array using indexing, numpy returns a numpy scalar object. Each time you access an element, a new scalar object is created, even if the value is the same.

In the above case only 'xt' and 'su' exist as python objects. When you take an element, xt[0], you instantiate a new python object, a scalar of type numpy.float64. These are new python objects and are thus given a new id, unless the interpreter realizes that you are trying to use this object twice (this is probably what is happening, although I do find it surprising that two numpy.float64 objects with different values are given the same id). **It could also happen that memory addresses get reused by the interpreter, giving you ids that have appeared before.**

In [179]:
print(type(su[0]))  
print(type(xt[0]))
#here you can see that both the element are of numpy.int64. So reusability of memory can be a possible answer

<class 'numpy.int64'>
<class 'numpy.int64'>


In [180]:
c = "sudh"

In [181]:
id(c) == id(su[0]) #but in this case, cleary both are of different type, therefore getting false

False