In [1]:
!pip install scikit-learn


In [2]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

In [3]:
from sklearn.model_selection import train_test_split

In [22]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [5]:
import pandas as pd
import numpy as np


In [7]:
X,y = make_classification(n_samples=1000,n_features=5, random_state=123)

In [8]:
X

array([[ 0.87728113, -0.59642825,  0.44019839, -0.52108094,  0.31432298],
       [ 0.55856502, -0.41451292,  0.813623  , -0.54325372,  0.14734302],
       [-0.90289911,  0.38303337, -0.71157267, -0.86768895, -0.67394137],
       ...,
       [ 1.7713853 , -0.96445461,  0.99337636,  0.40674576,  0.99881985],
       [-1.19977749,  0.48167954,  1.47831033, -1.31903526, -0.93698258],
       [ 0.33976266, -0.29183452, -0.82476815, -0.57191024,  0.02935597]])

In [9]:
y

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3, random_state = 42)

In [12]:
X_train.shape

(700, 5)

In [13]:
X_test.shape

(300, 5)

In [15]:
model = LogisticRegression()

In [16]:
model.fit(X_train,y_train)

LogisticRegression()

In [19]:
y_predict=model.predict(X_test)

In [20]:
accuracy_score(y_test,y_predict)

0.97

In [23]:
confusion_matrix(y_test,y_predict)

array([[149,   3],
       [  6, 142]])

this mean my logistic regression model is able to predict 94% data

In [24]:
model.score(X_train,y_train)

0.9428571428571428

Overfitting means trainacuracxy is very good and test accuracy is not good  

train accuraacy - test accuracy ?

10,20,30,40

lets say there is medical problem, which we are solving , here risk is very high


Underfitting means
train accuracy and test accuracy both are not good

Task


https://archive.ics.uci.edu/dataset/242/energy+efficiency

https://archive.ics.uci.edu/dataset/20/census+*income*

perform proper EDA
do feature engineering and preprocessing

model creation with logistic regression and perform hyperparameter tuning

evalute the model and print all the score and check with auc-roc score as well now give the conclusion which matrix is correct according to the problem stateemnt